# Generated by Django 4.1.4 on 2023-01-16 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_category_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postCategory',
            new_name='category',
        ),
    ]
