# Generated by Django 4.1.4 on 2023-02-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_rename_postcategory_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
    ]
